using System.ComponentModel;

// ------------------------------------------------------------------------------------------------
// <auto-generated>
//  This code was generated by a C# code generator
//  Generated at 18.10.2021 20:46:21
//
//  Warning: Do not make changes directly to this file; they will get overwritten on the next
//  code generation.
// </auto-generated>
// ------------------------------------------------------------------------------------------------
    
namespace GoldenLeague.Database.Enums
{

  /// <summary>
  /// Konfiguracja
  /// </summary>
  public enum ConfigKeys : int
  {
    //  Database information:
    //  ConnectionStringKey: EnumsDb; Table: [dbo].[ConfigDictionary]; IdColumn: [ConfigId]; NameColumn: [ConfigKey]; DescriptionColumn: [ConfigDescription]
    //  ConnectionString: Data Source=(LocalDb)\MSSQLLocalDB;Initial Catalog=GoldenLeague;Application Name=GoldenLeagueDB;Integrated Security=True
 
		/// <summary>
		/// Aktualny sezon
		/// </summary>
		[Description("Aktualny sezon")]
		CURRENT_SEASON_NO = 1,

  }
    
}
