//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Configuration;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace GoldenLeague.Database
{
	/// <summary>
	/// Database       : GoldenLeague
	/// Data Source    : (LocalDb)\MSSQLLocalDB
	/// Server Version : 13.00.4001
	/// </summary>
	public partial class GoldenLeagueDB : LinqToDB.Data.DataConnection
	{
		public ITable<ConfigDictionary> ConfigDictionary { get { return this.GetTable<ConfigDictionary>(); } }
		public ITable<MatchBetting>     MatchBetting     { get { return this.GetTable<MatchBetting>(); } }
		public ITable<Matches>          Matches          { get { return this.GetTable<Matches>(); } }
		public ITable<Teams>            Teams            { get { return this.GetTable<Teams>(); } }
		public ITable<Users>            Users            { get { return this.GetTable<Users>(); } }
		public ITable<VMatch>           VMatch           { get { return this.GetTable<VMatch>(); } }
		public ITable<VMatchBetting>    VMatchBetting    { get { return this.GetTable<VMatchBetting>(); } }

		public GoldenLeagueDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public GoldenLeagueDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public GoldenLeagueDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public GoldenLeagueDB(LinqToDbConnectionOptions<GoldenLeagueDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="ConfigDictionary")]
	public partial class ConfigDictionary
	{
		[Column(DataType=LinqToDB.DataType.Int32),                 PrimaryKey, Identity] public int    ConfigId          { get; set; } // int
		[Column(DataType=LinqToDB.DataType.VarChar,  Length=50),   NotNull             ] public string ConfigKey         { get; set; } // varchar(50)
		[Column(DataType=LinqToDB.DataType.NVarChar, Length=4000), NotNull             ] public string ConfigValue       { get; set; } // nvarchar(4000)
		[Column(DataType=LinqToDB.DataType.NVarChar, Length=4000), NotNull             ] public string ConfigDescription { get; set; } // nvarchar(4000)
	}

	[Table(Schema="dbo", Name="MatchBetting")]
	public partial class MatchBetting
	{
		[Column(DataType=LinqToDB.DataType.Guid),  PrimaryKey(1), NotNull] public Guid UserId        { get; set; } // uniqueidentifier
		[Column(DataType=LinqToDB.DataType.Guid),  PrimaryKey(2), NotNull] public Guid MatchId       { get; set; } // uniqueidentifier
		[Column(DataType=LinqToDB.DataType.Int32),    Nullable           ] public int? HomeTeamScore { get; set; } // int
		[Column(DataType=LinqToDB.DataType.Int32),    Nullable           ] public int? AwayTeamScore { get; set; } // int
		/// <summary>
		/// Liczba punktów za wytypowany wynik meczu (0 - nietrafiony, 1 - trafiony zwyciezca, 3 - trafiony wynik)
		/// </summary>
		[Column(DataType=LinqToDB.DataType.Int32),    Nullable           ] public int? BettingPoints { get; set; } // int

		#region Associations

		/// <summary>
		/// FK_MatchBetting_Matches
		/// </summary>
		[Association(ThisKey="MatchId", OtherKey="MatchId", CanBeNull=false, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK_MatchBetting_Matches", BackReferenceName="MatchBettings")]
		public Matches Match { get; set; }

		/// <summary>
		/// FK_MatchBetting_Users
		/// </summary>
		[Association(ThisKey="UserId", OtherKey="UserId", CanBeNull=false, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK_MatchBetting_Users", BackReferenceName="MatchBettings")]
		public Users User { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Matches")]
	public partial class Matches
	{
		[Column(DataType=LinqToDB.DataType.Guid),     PrimaryKey,  NotNull] public Guid     MatchId       { get; set; } // uniqueidentifier
		/// <summary>
		/// Sezon pilkarski (np. 2022 oznacza sezon 2021/22)
		/// </summary>
		[Column(DataType=LinqToDB.DataType.Int32),                 NotNull] public int      SeasonNo      { get; set; } // int
		/// <summary>
		/// Numer kolejki ligowej
		/// </summary>
		[Column(DataType=LinqToDB.DataType.Int32),                 NotNull] public int      GameweekNo    { get; set; } // int
		[Column(DataType=LinqToDB.DataType.DateTime),              NotNull] public DateTime MatchDateTime { get; set; } // datetime
		[Column(DataType=LinqToDB.DataType.Guid),                  NotNull] public Guid     HomeTeamId    { get; set; } // uniqueidentifier
		[Column(DataType=LinqToDB.DataType.Int32),       Nullable         ] public int?     HomeTeamScore { get; set; } // int
		[Column(DataType=LinqToDB.DataType.Guid),                  NotNull] public Guid     AwayTeamId    { get; set; } // uniqueidentifier
		[Column(DataType=LinqToDB.DataType.Int32),       Nullable         ] public int?     AwayTeamScore { get; set; } // int

		#region Associations

		/// <summary>
		/// FK_Matches_Teams_AwayTeam
		/// </summary>
		[Association(ThisKey="AwayTeamId", OtherKey="TeamId", CanBeNull=false, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK_Matches_Teams_AwayTeam", BackReferenceName="MatchesAwayTeams")]
		public Teams AwayTeam { get; set; }

		/// <summary>
		/// FK_Matches_Teams_HomeTeam
		/// </summary>
		[Association(ThisKey="HomeTeamId", OtherKey="TeamId", CanBeNull=false, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK_Matches_Teams_HomeTeam", BackReferenceName="MatchesHomeTeams")]
		public Teams HomeTeam { get; set; }

		/// <summary>
		/// FK_MatchBetting_Matches_BackReference
		/// </summary>
		[Association(ThisKey="MatchId", OtherKey="MatchId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MatchBetting> MatchBettings { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Teams")]
	public partial class Teams
	{
		[Column(DataType=LinqToDB.DataType.Guid),                 PrimaryKey, NotNull] public Guid   TeamId               { get; set; } // uniqueidentifier
		[Column(DataType=LinqToDB.DataType.NVarChar, Length=100),             NotNull] public string TeamName             { get; set; } // nvarchar(100)
		[Column(DataType=LinqToDB.DataType.NVarChar, Length=15),              NotNull] public string TeamNameShort        { get; set; } // nvarchar(15)
		[Column(DataType=LinqToDB.DataType.VarChar,  Length=3),               NotNull] public string TeamNameAbbreviation { get; set; } // varchar(3)

		#region Associations

		/// <summary>
		/// FK_Matches_Teams_AwayTeam_BackReference
		/// </summary>
		[Association(ThisKey="TeamId", OtherKey="AwayTeamId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Matches> MatchesAwayTeams { get; set; }

		/// <summary>
		/// FK_Matches_Teams_HomeTeam_BackReference
		/// </summary>
		[Association(ThisKey="TeamId", OtherKey="HomeTeamId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Matches> MatchesHomeTeams { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Users")]
	public partial class Users
	{
		[Column(DataType=LinqToDB.DataType.Guid),                 PrimaryKey,  NotNull] public Guid   UserId    { get; set; } // uniqueidentifier
		[Column(DataType=LinqToDB.DataType.NVarChar, Length=100),              NotNull] public string Login     { get; set; } // nvarchar(100)
		[Column(DataType=LinqToDB.DataType.NVarChar, Length=100),    Nullable         ] public string FullName  { get; set; } // nvarchar(100)
		[Column(DataType=LinqToDB.DataType.NVarChar, Length=100),              NotNull] public string Password  { get; set; } // nvarchar(100)
		[Column(DataType=LinqToDB.DataType.Boolean),                           NotNull] public bool   IsAdmin   { get; set; } // bit
		[Column(DataType=LinqToDB.DataType.Boolean),                           NotNull] public bool   IsDeleted { get; set; } // bit

		#region Associations

		/// <summary>
		/// FK_MatchBetting_Users_BackReference
		/// </summary>
		[Association(ThisKey="UserId", OtherKey="UserId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<MatchBetting> MatchBettings { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="vMatch", IsView=true)]
	public partial class VMatch
	{
		[Column(DataType=LinqToDB.DataType.Guid),                 NotNull    ] public Guid     MatchId                  { get; set; } // uniqueidentifier
		[Column(DataType=LinqToDB.DataType.Int32),                NotNull    ] public int      SeasonNo                 { get; set; } // int
		[Column(DataType=LinqToDB.DataType.Int32),                NotNull    ] public int      GameweekNo               { get; set; } // int
		[Column(DataType=LinqToDB.DataType.DateTime),             NotNull    ] public DateTime MatchDateTime            { get; set; } // datetime
		[Column(DataType=LinqToDB.DataType.Guid),                 NotNull    ] public Guid     HomeTeamId               { get; set; } // uniqueidentifier
		[Column(DataType=LinqToDB.DataType.NVarChar, Length=100), NotNull    ] public string   HomeTeamName             { get; set; } // nvarchar(100)
		[Column(DataType=LinqToDB.DataType.NVarChar, Length=15),  NotNull    ] public string   HomeTeamNameShort        { get; set; } // nvarchar(15)
		[Column(DataType=LinqToDB.DataType.VarChar,  Length=3),   NotNull    ] public string   HomeTeamNameAbbreviation { get; set; } // varchar(3)
		[Column(DataType=LinqToDB.DataType.Guid),                 NotNull    ] public Guid     AwayTeamId               { get; set; } // uniqueidentifier
		[Column(DataType=LinqToDB.DataType.NVarChar, Length=100), NotNull    ] public string   AwayTeamName             { get; set; } // nvarchar(100)
		[Column(DataType=LinqToDB.DataType.NVarChar, Length=15),  NotNull    ] public string   AwayTeamNameShort        { get; set; } // nvarchar(15)
		[Column(DataType=LinqToDB.DataType.VarChar,  Length=3),   NotNull    ] public string   AwayTeamNameAbbreviation { get; set; } // varchar(3)
		[Column(DataType=LinqToDB.DataType.Int32),                   Nullable] public int?     HomeTeamScore            { get; set; } // int
		[Column(DataType=LinqToDB.DataType.Int32),                   Nullable] public int?     AwayTeamScore            { get; set; } // int
	}

	[Table(Schema="dbo", Name="vMatchBetting", IsView=true)]
	public partial class VMatchBetting
	{
		[Column(DataType=LinqToDB.DataType.Guid),                 NotNull    ] public Guid     UserId                   { get; set; } // uniqueidentifier
		[Column(DataType=LinqToDB.DataType.Guid),                 NotNull    ] public Guid     MatchId                  { get; set; } // uniqueidentifier
		[Column(DataType=LinqToDB.DataType.Int32),                NotNull    ] public int      SeasonNo                 { get; set; } // int
		[Column(DataType=LinqToDB.DataType.Int32),                NotNull    ] public int      GameweekNo               { get; set; } // int
		[Column(DataType=LinqToDB.DataType.DateTime),             NotNull    ] public DateTime MatchDateTime            { get; set; } // datetime
		[Column(DataType=LinqToDB.DataType.Guid),                 NotNull    ] public Guid     HomeTeamId               { get; set; } // uniqueidentifier
		[Column(DataType=LinqToDB.DataType.NVarChar, Length=100), NotNull    ] public string   HomeTeamName             { get; set; } // nvarchar(100)
		[Column(DataType=LinqToDB.DataType.NVarChar, Length=15),  NotNull    ] public string   HomeTeamNameShort        { get; set; } // nvarchar(15)
		[Column(DataType=LinqToDB.DataType.VarChar,  Length=3),   NotNull    ] public string   HomeTeamNameAbbreviation { get; set; } // varchar(3)
		[Column(DataType=LinqToDB.DataType.Guid),                 NotNull    ] public Guid     AwayTeamId               { get; set; } // uniqueidentifier
		[Column(DataType=LinqToDB.DataType.NVarChar, Length=100), NotNull    ] public string   AwayTeamName             { get; set; } // nvarchar(100)
		[Column(DataType=LinqToDB.DataType.NVarChar, Length=15),  NotNull    ] public string   AwayTeamNameShort        { get; set; } // nvarchar(15)
		[Column(DataType=LinqToDB.DataType.VarChar,  Length=3),   NotNull    ] public string   AwayTeamNameAbbreviation { get; set; } // varchar(3)
		[Column(DataType=LinqToDB.DataType.Int32),                   Nullable] public int?     HomeTeamScoreActual      { get; set; } // int
		[Column(DataType=LinqToDB.DataType.Int32),                   Nullable] public int?     HomeTeamScoreBet         { get; set; } // int
		[Column(DataType=LinqToDB.DataType.Int32),                   Nullable] public int?     AwayTeamScoreActual      { get; set; } // int
		[Column(DataType=LinqToDB.DataType.Int32),                   Nullable] public int?     AwayTeamScoreBet         { get; set; } // int
		[Column(DataType=LinqToDB.DataType.Int32),                   Nullable] public int?     BettingPoints            { get; set; } // int
	}

	public static partial class GoldenLeagueDBStoredProcedures
	{
		#region GetUserMatchBetting

		public static IEnumerable<VMatchBetting> GetUserMatchBetting(this GoldenLeagueDB dataConnection, Guid? @UserId, int? @SeasonNo)
		{
			return dataConnection.QueryProc<VMatchBetting>("[dbo].[GetUserMatchBetting]",
				new DataParameter("@UserId",   @UserId,   LinqToDB.DataType.Guid),
				new DataParameter("@SeasonNo", @SeasonNo, LinqToDB.DataType.Int32));
		}

		#endregion

		#region SetMatchBettingPointsForEmptyBetting

		public static int SetMatchBettingPointsForEmptyBetting(this GoldenLeagueDB dataConnection)
		{
			return dataConnection.ExecuteProc("[dbo].[SetMatchBettingPointsForEmptyBetting]");
		}

		#endregion

		#region SpAlterdiagram

		public static int SpAlterdiagram(this GoldenLeagueDB dataConnection, string @diagramname, int? @owner_id, int? @version, byte[] @definition)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_alterdiagram]",
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    LinqToDB.DataType.Int32),
				new DataParameter("@version",     @version,     LinqToDB.DataType.Int32),
				new DataParameter("@definition",  @definition,  LinqToDB.DataType.VarBinary));
		}

		#endregion

		#region SpCreatediagram

		public static int SpCreatediagram(this GoldenLeagueDB dataConnection, string @diagramname, int? @owner_id, int? @version, byte[] @definition)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_creatediagram]",
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    LinqToDB.DataType.Int32),
				new DataParameter("@version",     @version,     LinqToDB.DataType.Int32),
				new DataParameter("@definition",  @definition,  LinqToDB.DataType.VarBinary));
		}

		#endregion

		#region SpDropdiagram

		public static int SpDropdiagram(this GoldenLeagueDB dataConnection, string @diagramname, int? @owner_id)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_dropdiagram]",
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    LinqToDB.DataType.Int32));
		}

		#endregion

		#region SpHelpdiagramdefinition

		public static IEnumerable<SpHelpdiagramdefinitionResult> SpHelpdiagramdefinition(this GoldenLeagueDB dataConnection, string @diagramname, int? @owner_id)
		{
			return dataConnection.QueryProc<SpHelpdiagramdefinitionResult>("[dbo].[sp_helpdiagramdefinition]",
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    LinqToDB.DataType.Int32));
		}

		public partial class SpHelpdiagramdefinitionResult
		{
			public int?   version    { get; set; }
			public byte[] definition { get; set; }
		}

		#endregion

		#region SpHelpdiagrams

		public static IEnumerable<SpHelpdiagramsResult> SpHelpdiagrams(this GoldenLeagueDB dataConnection, string @diagramname, int? @owner_id)
		{
			return dataConnection.QueryProc<SpHelpdiagramsResult>("[dbo].[sp_helpdiagrams]",
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    LinqToDB.DataType.Int32));
		}

		public partial class SpHelpdiagramsResult
		{
			public string Database { get; set; }
			public string Name     { get; set; }
			public int    ID       { get; set; }
			public string Owner    { get; set; }
			public int    OwnerID  { get; set; }
		}

		#endregion

		#region SpRenamediagram

		public static int SpRenamediagram(this GoldenLeagueDB dataConnection, string @diagramname, int? @owner_id, string @new_diagramname)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_renamediagram]",
				new DataParameter("@diagramname",     @diagramname,     LinqToDB.DataType.NVarChar),
				new DataParameter("@owner_id",        @owner_id,        LinqToDB.DataType.Int32),
				new DataParameter("@new_diagramname", @new_diagramname, LinqToDB.DataType.NVarChar));
		}

		#endregion
	}

	public static partial class SqlFunctions
	{
		#region FnDiagramobjects

		[Sql.Function(Name="dbo.fn_diagramobjects", ServerSideOnly=true)]
		public static int? FnDiagramobjects()
		{
			throw new InvalidOperationException();
		}

		#endregion
	}

	public static partial class TableExtensions
	{
		public static ConfigDictionary Find(this ITable<ConfigDictionary> table, int ConfigId)
		{
			return table.FirstOrDefault(t =>
				t.ConfigId == ConfigId);
		}

		public static MatchBetting Find(this ITable<MatchBetting> table, Guid UserId, Guid MatchId)
		{
			return table.FirstOrDefault(t =>
				t.UserId  == UserId &&
				t.MatchId == MatchId);
		}

		public static Matches Find(this ITable<Matches> table, Guid MatchId)
		{
			return table.FirstOrDefault(t =>
				t.MatchId == MatchId);
		}

		public static Teams Find(this ITable<Teams> table, Guid TeamId)
		{
			return table.FirstOrDefault(t =>
				t.TeamId == TeamId);
		}

		public static Users Find(this ITable<Users> table, Guid UserId)
		{
			return table.FirstOrDefault(t =>
				t.UserId == UserId);
		}
	}
}

#pragma warning restore 1591
