//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace GoldenLeague.Database
{
	/// <summary>
	/// Database       : GoldenLeague
	/// Data Source    : (LocalDb)\MSSQLLocalDB
	/// Server Version : 13.00.4001
	/// </summary>
	public partial class GoldenLeagueDB : LinqToDB.Data.DataConnection
	{
		public ITable<Users> Users { get { return this.GetTable<Users>(); } }

		public GoldenLeagueDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public GoldenLeagueDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public GoldenLeagueDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public GoldenLeagueDB(LinqToDbConnectionOptions<GoldenLeagueDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="Users")]
	public partial class Users
	{
		[PrimaryKey, NotNull] public Guid   UserId   { get; set; } // uniqueidentifier
		[Column,     NotNull] public string Login    { get; set; } // nvarchar(50)
		[Column,     NotNull] public string FullName { get; set; } // nvarchar(100)
		[Column,     NotNull] public string Password { get; set; } // nvarchar(50)
		[Column,     NotNull] public bool   IsAdmin  { get; set; } // bit
	}

	public static partial class TableExtensions
	{
		public static Users Find(this ITable<Users> table, Guid UserId)
		{
			return table.FirstOrDefault(t =>
				t.UserId == UserId);
		}
	}
}

#pragma warning restore 1591
